import type {
  CSRGrant,
  Donor,
  EndowmentFund,
  PipelineOpportunity,
} from "./types";

export const initialFunds: EndowmentFund[] = [
  {
    id: "fund-1",
    name: "Prof. R.K. Sharma Memorial Endowment",
    code: "END-2019-014",
    corpusType: "Restricted",
    corpusValue: 12500000,
    currentBalance: 14180000,
    purpose: "Merit scholarships for undergraduate students in Civil Engineering",
    donorName: "Sharma Family Trust",
    establishedDate: "2019-04-12",
    status: "Active",
    yieldRecords: [
      {
        id: "fy-1",
        year: "2023-24",
        openingBalance: 13020000,
        interestEarned: 912000,
        disbursed: 480000,
        closingBalance: 13452000,
        recordedBy: "Anita Rao",
        recordedAt: "2024-04-30",
      },
      {
        id: "fy-2",
        year: "2024-25",
        openingBalance: 13452000,
        interestEarned: 1148000,
        disbursed: 420000,
        closingBalance: 14180000,
        recordedBy: "Anita Rao",
        recordedAt: "2025-04-28",
      },
    ],
  },
  {
    id: "fund-2",
    name: "IIT Mandi Alumni General Corpus",
    code: "END-2016-002",
    corpusType: "Unrestricted",
    corpusValue: 30000000,
    currentBalance: 36740000,
    purpose: "Institute discretionary use — infrastructure and student welfare",
    donorName: "Alumni Association, IIT Mandi",
    establishedDate: "2016-08-01",
    status: "Active",
    yieldRecords: [
      {
        id: "fy-3",
        year: "2023-24",
        openingBalance: 33210000,
        interestEarned: 2380000,
        disbursed: 1100000,
        closingBalance: 34490000,
        recordedBy: "Vikram Nair",
        recordedAt: "2024-05-02",
      },
      {
        id: "fy-4",
        year: "2024-25",
        openingBalance: 34490000,
        interestEarned: 2650000,
        disbursed: 400000,
        closingBalance: 36740000,
        recordedBy: "Vikram Nair",
        recordedAt: "2025-05-01",
      },
    ],
  },
  {
    id: "fund-3",
    name: "Women in STEM Fellowship Fund",
    code: "END-2021-031",
    corpusType: "Restricted",
    corpusValue: 8000000,
    currentBalance: 8960000,
    purpose: "Fellowships for women graduate researchers in core sciences",
    donorName: "Meera Krishnan (Alumna, B.Tech 2004)",
    establishedDate: "2021-11-20",
    status: "Active",
    yieldRecords: [
      {
        id: "fy-5",
        year: "2024-25",
        openingBalance: 8520000,
        interestEarned: 610000,
        disbursed: 170000,
        closingBalance: 8960000,
        recordedBy: "Anita Rao",
        recordedAt: "2025-04-15",
      },
    ],
  },
  {
    id: "fund-4",
    name: "Rural Innovation Chair Endowment",
    code: "END-2014-006",
    corpusType: "Restricted",
    corpusValue: 15000000,
    currentBalance: 15000000,
    purpose: "Endowed chair professorship for rural technology innovation",
    donorName: "Himalayan Development Foundation",
    establishedDate: "2014-02-10",
    status: "Frozen",
    yieldRecords: [
      {
        id: "fy-6",
        year: "2022-23",
        openingBalance: 15000000,
        interestEarned: 0,
        disbursed: 0,
        closingBalance: 15000000,
        recordedBy: "Vikram Nair",
        recordedAt: "2023-04-10",
      },
    ],
  },
  {
    id: "fund-5",
    name: "Legacy Batch of 1998 Scholarship Corpus",
    code: "END-2010-001",
    corpusType: "Restricted",
    corpusValue: 4000000,
    currentBalance: 0,
    purpose: "Fully disbursed — scholarships for Batch 1998 reunion pledge",
    donorName: "Batch of 1998 Alumni Group",
    establishedDate: "2010-06-01",
    status: "Closed",
    yieldRecords: [],
  },
];

export const initialGrants: CSRGrant[] = [
  {
    id: "grant-1",
    companyName: "Tata Power Ltd.",
    grantTitle: "Solar Microgrid Pilot for Himalayan Villages",
    csrActSection: "Schedule VII (iv) — Environmental Sustainability",
    totalAmount: 9500000,
    sanctionedAmount: 9500000,
    disbursedAmount: 3200000,
    status: "Active",
    startDate: "2024-09-01",
    endDate: "2026-03-31",
    makerName: "Rohan Verma",
    approverName: "Dean, DORA",
    milestones: [
      {
        id: "gm-1",
        title: "Site survey & village selection report",
        dueDate: "2024-11-30",
        amount: 1200000,
        status: "Disbursed",
        evidenceNote: "Report submitted, verified by field team.",
        approvedBy: "Dean, DORA",
        disbursedBy: "Finance Cell",
      },
      {
        id: "gm-2",
        title: "Microgrid installation — Phase 1 (3 villages)",
        dueDate: "2025-06-30",
        amount: 3200000,
        status: "Disbursed",
        evidenceNote: "Installation photos + utilization certificate on file.",
        approvedBy: "Dean, DORA",
        disbursedBy: "Finance Cell",
      },
      {
        id: "gm-3",
        title: "Microgrid installation — Phase 2 (4 villages)",
        dueDate: "2025-12-31",
        amount: 3600000,
        status: "Submitted",
        evidenceNote: "UC and photos uploaded, pending review.",
      },
      {
        id: "gm-4",
        title: "Impact assessment & closure report",
        dueDate: "2026-03-15",
        amount: 1500000,
        status: "Pending",
      },
    ],
    auditTrail: [
      { id: "a1", action: "Grant created", actor: "Rohan Verma", role: "CSR_GRANTS_OFFICER", timestamp: "2024-08-20" },
      { id: "a2", action: "Grant approved", actor: "Dean, DORA", role: "DEAN_APPROVER", timestamp: "2024-08-28" },
      { id: "a3", action: "Milestone 1 disbursed", actor: "Finance Cell", role: "FINANCE", timestamp: "2024-12-05" },
      { id: "a4", action: "Milestone 2 disbursed", actor: "Finance Cell", role: "FINANCE", timestamp: "2025-07-10" },
    ],
  },
  {
    id: "grant-2",
    companyName: "Infosys Foundation",
    grantTitle: "Digital Literacy Lab for Government Schools, Mandi District",
    csrActSection: "Schedule VII (ii) — Education",
    totalAmount: 4200000,
    sanctionedAmount: 4200000,
    disbursedAmount: 1400000,
    status: "Active",
    startDate: "2025-01-15",
    endDate: "2025-12-31",
    makerName: "Rohan Verma",
    approverName: "Dean, DORA",
    milestones: [
      {
        id: "gm-5",
        title: "Lab setup — 5 schools",
        dueDate: "2025-04-30",
        amount: 1400000,
        status: "Disbursed",
        evidenceNote: "Handover certificates collected.",
        approvedBy: "Dean, DORA",
        disbursedBy: "Finance Cell",
      },
      {
        id: "gm-6",
        title: "Teacher training workshops (3 batches)",
        dueDate: "2025-09-30",
        amount: 1300000,
        status: "UnderReview",
        evidenceNote: "Attendance sheets + vendor invoice submitted.",
      },
      {
        id: "gm-7",
        title: "Year-end learning outcome survey",
        dueDate: "2025-12-15",
        amount: 1500000,
        status: "Pending",
      },
    ],
    auditTrail: [
      { id: "a5", action: "Grant created", actor: "Rohan Verma", role: "CSR_GRANTS_OFFICER", timestamp: "2024-12-10" },
      { id: "a6", action: "Grant approved", actor: "Dean, DORA", role: "DEAN_APPROVER", timestamp: "2024-12-18" },
      { id: "a7", action: "Milestone 1 disbursed", actor: "Finance Cell", role: "FINANCE", timestamp: "2025-05-02" },
    ],
  },
  {
    id: "grant-3",
    companyName: "Hindustan Unilever Ltd.",
    grantTitle: "Water Purification Units — Public Health Initiative",
    csrActSection: "Schedule VII (i) — Health & Sanitation",
    totalAmount: 6000000,
    sanctionedAmount: 0,
    disbursedAmount: 0,
    status: "PendingApproval",
    startDate: "2026-01-01",
    endDate: "2027-06-30",
    makerName: "Rohan Verma",
    milestones: [
      { id: "gm-8", title: "Needs assessment across 12 panchayats", dueDate: "2026-03-31", amount: 900000, status: "Pending" },
      { id: "gm-9", title: "Unit installation — Phase 1", dueDate: "2026-09-30", amount: 2600000, status: "Pending" },
      { id: "gm-10", title: "Unit installation — Phase 2 + closure", dueDate: "2027-05-31", amount: 2500000, status: "Pending" },
    ],
    auditTrail: [
      { id: "a8", action: "Grant created, submitted for approval", actor: "Rohan Verma", role: "CSR_GRANTS_OFFICER", timestamp: "2025-12-02" },
    ],
  },
  {
    id: "grant-4",
    companyName: "Wipro CSR",
    grantTitle: "AI/ML Skilling Bootcamp for Engineering Students",
    csrActSection: "Schedule VII (ii) — Education",
    totalAmount: 2800000,
    sanctionedAmount: 2800000,
    disbursedAmount: 2800000,
    status: "Completed",
    startDate: "2024-02-01",
    endDate: "2024-11-30",
    makerName: "Rohan Verma",
    approverName: "Dean, DORA",
    milestones: [
      { id: "gm-11", title: "Bootcamp delivery — 200 students", dueDate: "2024-08-31", amount: 1800000, status: "Disbursed", approvedBy: "Dean, DORA", disbursedBy: "Finance Cell" },
      { id: "gm-12", title: "Placement outcomes report", dueDate: "2024-11-30", amount: 1000000, status: "Disbursed", approvedBy: "Dean, DORA", disbursedBy: "Finance Cell" },
    ],
    auditTrail: [
      { id: "a9", action: "Grant created", actor: "Rohan Verma", role: "CSR_GRANTS_OFFICER", timestamp: "2024-01-10" },
      { id: "a10", action: "Grant approved", actor: "Dean, DORA", role: "DEAN_APPROVER", timestamp: "2024-01-18" },
      { id: "a11", action: "Grant marked completed", actor: "Rohan Verma", role: "CSR_GRANTS_OFFICER", timestamp: "2024-12-05" },
    ],
  },
  {
    id: "grant-5",
    companyName: "Adani Foundation",
    grantTitle: "Vocational Training Center — Furniture & Fabrication",
    csrActSection: "Schedule VII (ii) — Vocational Skills",
    totalAmount: 5100000,
    sanctionedAmount: 0,
    disbursedAmount: 0,
    status: "Rejected",
    startDate: "2025-06-01",
    endDate: "2026-05-31",
    makerName: "Rohan Verma",
    approverName: "Dean, DORA",
    milestones: [
      { id: "gm-13", title: "Center setup", dueDate: "2025-09-30", amount: 3000000, status: "Pending" },
      { id: "gm-14", title: "First cohort completion", dueDate: "2026-03-31", amount: 2100000, status: "Pending" },
    ],
    auditTrail: [
      { id: "a12", action: "Grant created, submitted for approval", actor: "Rohan Verma", role: "CSR_GRANTS_OFFICER", timestamp: "2025-05-01" },
      { id: "a13", action: "Grant rejected — overlaps with existing MSDE scheme", actor: "Dean, DORA", role: "DEAN_APPROVER", timestamp: "2025-05-14" },
    ],
  },
];

export const initialDonors: Donor[] = [
  {
    id: "donor-1",
    name: "Meera Krishnan",
    type: "Alumni",
    email: "meera.krishnan@example.com",
    phone: "+91 98765 43210",
    status: "Active",
    totalGiving: 8000000,
    relationshipOwner: "Priya Menon",
    lastContactDate: "2026-07-02",
    tags: ["B.Tech 2004", "STEM Fellowship", "Repeat donor"],
    interactions: [
      { id: "i1", date: "2026-07-02", type: "Call", summary: "Discussed expanding fellowship to 2 more PhD scholars.", by: "Priya Menon" },
      { id: "i2", date: "2026-03-15", type: "Meeting", summary: "Campus visit — met current fellowship recipients.", by: "Priya Menon" },
    ],
  },
  {
    id: "donor-2",
    name: "Tata Power Ltd.",
    type: "Corporate",
    email: "csr.desk@tatapower.example.com",
    phone: "+91 22 6665 8282",
    status: "Active",
    totalGiving: 9500000,
    relationshipOwner: "Rohan Verma",
    lastContactDate: "2026-08-01",
    tags: ["CSR Partner", "Renewable Energy"],
    interactions: [
      { id: "i3", date: "2026-08-01", type: "Email", summary: "Sent Phase 2 progress update and UC for microgrid project.", by: "Rohan Verma" },
    ],
  },
  {
    id: "donor-3",
    name: "Vikram Nair",
    type: "Alumni",
    email: "vikram.nair@example.com",
    phone: "+91 90210 11223",
    status: "Prospect",
    totalGiving: 0,
    relationshipOwner: "Priya Menon",
    lastContactDate: "2026-06-18",
    tags: ["B.Tech 2011", "Fintech founder"],
    interactions: [
      { id: "i4", date: "2026-06-18", type: "Meeting", summary: "First outreach at alumni meet — interested in incubation fund.", by: "Priya Menon" },
    ],
  },
  {
    id: "donor-4",
    name: "Infosys Foundation",
    type: "Foundation",
    email: "grants@infosysfoundation.example.com",
    phone: "+91 80 4116 9999",
    status: "Active",
    totalGiving: 4200000,
    relationshipOwner: "Rohan Verma",
    lastContactDate: "2026-07-20",
    tags: ["CSR Partner", "Education"],
    interactions: [
      { id: "i5", date: "2026-07-20", type: "Call", summary: "Teacher training milestone review call scheduled.", by: "Rohan Verma" },
    ],
  },
  {
    id: "donor-5",
    name: "Ananya Suresh",
    type: "Individual",
    email: "ananya.suresh@example.com",
    phone: "+91 99887 76655",
    status: "Lapsed",
    totalGiving: 250000,
    relationshipOwner: "Priya Menon",
    lastContactDate: "2025-01-10",
    tags: ["Parent donor"],
    interactions: [
      { id: "i6", date: "2025-01-10", type: "Email", summary: "Thank-you note sent for last year's contribution; no response since.", by: "Priya Menon" },
    ],
  },
  {
    id: "donor-6",
    name: "Himalayan Development Foundation",
    type: "Foundation",
    email: "contact@hdf.example.org",
    phone: "+91 1905 222 100",
    status: "Active",
    totalGiving: 15000000,
    relationshipOwner: "Priya Menon",
    lastContactDate: "2026-05-11",
    tags: ["Endowed Chair", "Rural Development"],
    interactions: [
      { id: "i7", date: "2026-05-11", type: "Meeting", summary: "Discussed unfreezing chair endowment pending new faculty hire.", by: "Priya Menon" },
    ],
  },
  {
    id: "donor-7",
    name: "Arjun Mehta",
    type: "Alumni",
    email: "arjun.mehta@example.com",
    phone: "+91 98123 45678",
    status: "Prospect",
    totalGiving: 0,
    relationshipOwner: "Priya Menon",
    lastContactDate: "2026-07-28",
    tags: ["M.Tech 2015", "Working at Google"],
    interactions: [
      { id: "i8", date: "2026-07-28", type: "Email", summary: "Sent giving-back deck after LinkedIn outreach.", by: "Priya Menon" },
    ],
  },
  {
    id: "donor-8",
    name: "Wipro CSR",
    type: "Corporate",
    email: "csr@wipro.example.com",
    phone: "+91 80 2844 0011",
    status: "Lapsed",
    totalGiving: 2800000,
    relationshipOwner: "Rohan Verma",
    lastContactDate: "2025-01-05",
    tags: ["CSR Partner", "Past project completed"],
    interactions: [
      { id: "i9", date: "2025-01-05", type: "Call", summary: "Project closure call; no new CSR budget confirmed for this FY.", by: "Rohan Verma" },
    ],
  },
];

export const initialOpportunities: PipelineOpportunity[] = [
  {
    id: "opp-1",
    donorName: "Vikram Nair",
    opportunityName: "Fintech Incubation Seed Fund",
    stage: "Identification",
    estimatedAmount: 2500000,
    probability: 15,
    expectedCloseDate: "2026-12-31",
    owner: "Priya Menon",
  },
  {
    id: "opp-2",
    donorName: "Arjun Mehta",
    opportunityName: "M.Tech Alumni Giving Circle",
    stage: "Identification",
    estimatedAmount: 500000,
    probability: 20,
    expectedCloseDate: "2026-11-15",
    owner: "Priya Menon",
  },
  {
    id: "opp-3",
    donorName: "Himalayan Development Foundation",
    opportunityName: "Rural Innovation Chair — Unfreeze & Top-up",
    stage: "Cultivation",
    estimatedAmount: 5000000,
    probability: 35,
    expectedCloseDate: "2026-10-01",
    owner: "Priya Menon",
  },
  {
    id: "opp-4",
    donorName: "Reliance Foundation",
    opportunityName: "Clean Energy Research Grant",
    stage: "Cultivation",
    estimatedAmount: 12000000,
    probability: 30,
    expectedCloseDate: "2027-01-31",
    owner: "Rohan Verma",
  },
  {
    id: "opp-5",
    donorName: "Infosys Foundation",
    opportunityName: "Digital Literacy Lab — Phase 2 Expansion",
    stage: "Solicitation",
    estimatedAmount: 3500000,
    probability: 55,
    expectedCloseDate: "2026-09-30",
    owner: "Rohan Verma",
  },
  {
    id: "opp-6",
    donorName: "Meera Krishnan",
    opportunityName: "STEM Fellowship — 2 Additional Seats",
    stage: "Negotiation",
    estimatedAmount: 3200000,
    probability: 70,
    expectedCloseDate: "2026-09-05",
    owner: "Priya Menon",
  },
  {
    id: "opp-7",
    donorName: "Tata Power Ltd.",
    opportunityName: "Solar Microgrid — Phase 3 Extension",
    stage: "Negotiation",
    estimatedAmount: 6800000,
    probability: 65,
    expectedCloseDate: "2026-10-15",
    owner: "Rohan Verma",
  },
  {
    id: "opp-8",
    donorName: "HDFC Bank CSR",
    opportunityName: "Financial Literacy Outreach Program",
    stage: "ClosedWon",
    estimatedAmount: 1800000,
    probability: 100,
    expectedCloseDate: "2026-06-01",
    owner: "Rohan Verma",
  },
  {
    id: "opp-9",
    donorName: "Adani Foundation",
    opportunityName: "Vocational Training Center",
    stage: "ClosedLost",
    estimatedAmount: 5100000,
    probability: 0,
    expectedCloseDate: "2025-05-14",
    owner: "Rohan Verma",
    notes: "Rejected at approval stage — overlapped with existing MSDE scheme.",
  },
];
